In [1]:
port = []
string = "FTP Server is running on ports:"
string2 = " Is the server online"
online = True
print(string + str(port) + string2 + str(online))

FTP Server is running on ports:[] Is the server onlineTrue


In [2]:
port.append(21)
port.append(21)
port.append(22)
port.append(83)
print(string + str(port) + string2 + str(online))

FTP Server is running on ports:[21, 21, 22, 83] Is the server onlineTrue


In [3]:
port.remove(83)
print(string + str(port) + string2 + str(online))

FTP Server is running on ports:[21, 21, 22] Is the server onlineTrue


In [4]:
print("Our list has " + str(port.count(21)) + " Elements")

Our list has 2 Elements


In [5]:
print(len(port))

3


****

In [6]:
mylist = [1,2,3,'Hello','World']
mysecondlist = ['Thomos','Lara','Julia']

In [7]:
def printloop():
    for i in mylist:
        print(i)

In [8]:
printloop()

1
2
3
Hello
World


In [9]:
def printloop(list):
    for i in list:
        print(i)

printloop(mylist)
printloop(mysecondlist)

1
2
3
Hello
World
Thomos
Lara
Julia


In [10]:
def printloop(list):
    for i in list:
        print("This is a value :" + str(i))
        
printloop(mylist)
printloop(mysecondlist)

This is a value :1
This is a value :2
This is a value :3
This is a value :Hello
This is a value :World
This is a value :Thomos
This is a value :Lara
This is a value :Julia


In [11]:
# definations within definations
def thisismylist(value):
    mylist = [1,2,3,'hello','world']
    mylist.append(value)
    printloop(mylist)

In [12]:
thisismylist('amjad')

This is a value :1
This is a value :2
This is a value :3
This is a value :hello
This is a value :world
This is a value :amjad


In [13]:
currentyear = input("What year is it :")
yearborn = input("At what year you were born :")

try:
    print(int(currentyear) - int(yearborn))
except(ValueError):
    print("Input was invalid")

What year is it :2021
At what year you were born :1993
28


In [14]:
import numpy as np

In [15]:
np.linspace(2.0,3.0,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [16]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [17]:
np.logspace(2.0,3.0,num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [18]:
np.logspace(2.0,3.0,num=4,endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

***

## Array

In [19]:
from array import *

In [20]:
## if we dont want use arr every time we use "from function"

In [21]:
vals = array("i",[3,6,8,10])
print(vals)

array('i', [3, 6, 8, 10])


In [22]:
val = array('i',[5,-9,6,7,0])
for e in val:
    print(e)

5
-9
6
7
0


In [23]:
val = array('i',[5,-9,6,7,0])
newarr = array(val.typecode,(a for a in val))
for e in newarr:
    print(e)

5
-9
6
7
0


In [24]:
val = array('i',[5,-9,6,7,0])
newarr = array(val.typecode,(a*a for a in val))
i = 0
while i<len(newarr):
    print(newarr[i])
    i+=1

25
81
36
49
0


In [25]:
# if we dont know how many we have to print depends upon the "user"
arr = array('i',[])
n  = int(input("Enter the length of the Range :"))
for i in range(n):
    x = int(input("Enter the next value :"))
    arr.append(x)
print(arr)

Enter the length of the Range :10
Enter the next value :5
Enter the next value :5
Enter the next value :5
Enter the next value :5
Enter the next value :5
Enter the next value :5
Enter the next value :5
Enter the next value :5
Enter the next value :5
Enter the next value :5
array('i', [5, 5, 5, 5, 5, 5, 5, 5, 5, 5])


In [26]:
# if we dont know how many we have to print depends upon the "user"
arr = array('i',[])
n  = int(input("Enter the length of the Range :"))
for i in range(n):
    x = int(input("Enter the next value :"))
    arr.append(x)
print(arr)

val = int(input("Enter the value for search :"))
k=0
for e in arr:
    if e==val:
        print(k)
        break
    k+=1    
else:
    print("Enter the right one")
    
    

Enter the length of the Range :5
Enter the next value :1
Enter the next value :1
Enter the next value :1
Enter the next value :1
Enter the next value :1
array('i', [1, 1, 1, 1, 1])
Enter the value for search :3
Enter the right one


***

### Functions

In [27]:
def add_sub(x,y):
    c = x+y
    d = x-y
    return c,d
    
result = add_sub(5,4)
print(result)

(9, 1)


In [28]:
# placing same memory
def update(list):
    print(id(list))
    list[1] = 25
    print(id(list))
    print("x" ,list)
    
list = [10,20,30]
print(id(list))
update(list)
print("list",list)

2469981280576
2469981280576
2469981280576
x [10, 25, 30]
list [10, 25, 30]


In [29]:
#to overite the def fuctions
def sum(a,*b):
    print('a:',a)
    print('b:', b)
sum(5,6,7,8,9)

a: 5
b: (6, 7, 8, 9)


In [30]:
def sum(a,*b):
    print('a:',a)
    print('b:',b)
    c = a
    for i in b:
        c = c + i
    print('c:(a+b) = ',c)

sum(5,6,7,8,9,25)
        

a: 5
b: (6, 7, 8, 9, 25)
c:(a+b) =  60


In [31]:
def sum(*b):
    c = 0
    for i in b:
        c = c + i
    print(c)
sum(5,6,7,8,9,25)
        

60


### if we want to add multiple data we use " **   "

In [32]:
def person(name, **data):
    print('Name:',name)
    
    for i,j in data.items():
        print(i,j)
        
person('navin',age= 28,city='Mumbai',mob = 9393842525)

Name: navin
age 28
city Mumbai
mob 9393842525


### OOPS

In [33]:
#printing -->complex numbers x+yj

class ComplexNumber:
    def __init__(self,real,img):
        self.real = real
        self.img = img
        print("{}+{}j".format(self.real,self.img))
num1 = ComplexNumber(5,2)
num2 = ComplexNumber(10,20)
print(num1) # to print sepecific num we use magical function

5+2j
10+20j


In [34]:
class ComplexNumber:
    def __init__(self,real,img):
        self.real = real
        self.img = img
    def __str__(self):
        return "{}+{}j".format(self.real,self.img)
num1 = ComplexNumber(5,2)
num2 = ComplexNumber(12,34)
print(num1)
print(num2)
        

5+2j
12+34j


In [35]:
# adding two numnbers "num1+num2"
class ComplexNumber:
    def __init__(self,real,img):
        self.real = real
        self.img = img
        
    def __str__(self):
        return "{}+{}j".format(self.real,self.img)
    
    def __add__(self,other):
        x = self.real + other.real
        y = self.img + other.img
        return "{}+{}j".format(x,y)

num1 = ComplexNumber(5,2)
num2 = ComplexNumber(12,34)
print(num1)
print(num2)
print(num1+num2)
        

5+2j
12+34j
17+36j


In [36]:
class Car:
    def __init__(self,milage,color):
        self.milage = milage
        self.color = color
    def getMilage(self):
        return self.milage
    def getColor(self):
        return self.color
    def greet(self):
        print("Hello I am a Car!")

model1 = Car(65,"Black")
model2 = Car(45,"Grey")
print(model1.getMilage())
model2.greet()

65
Hello I am a Car!


### Inheariant Class

In [37]:
class Animals:
    def __init__(self,color):
        self.color = color
    def introduce(self):
        print("Making sounds")
    def makeSound(self):
        print("Making Sound")

class Dog:
    def __init__(self,color):
        self.color = color
    def introduce(self):
        print("Hello I am an Animal")
    def makeSound(self):
        print("Making Sounds")
        
wild_animals = Animals("Brown")
puppy = Dog("White")
wild_animals.makeSound()
    

Making Sound


In [38]:
# Alternate method

class Animal:
    
    def __init__(self,color):
        self.color = color
        
    def introduce(self):
        return print("Hello i am an Animal")
        
    def makeSound(self):
        return print("Making Sound")

class Dog(Animal):#--->class within a class
    
    def takeCare(self):
        return print("I am taking care of you")
        
wild_animal = Animal("Brown")
puppy = Dog("White")
wild_animal.makeSound()
puppy.introduce()

Making Sound
Hello i am an Animal


In [39]:
class Animal:
    
    def __init__(self,color):
        self.color = color
        
    def introduce(self):
        return print("Hello i am an Animal")
        
    def makeSound(self):
        return print("Making Sound")

class Dog(Animal):#--->class within a class
    
    def takeCare(self):
        return print("I am taking care of you")
    def makeSound(self):
        print("Bow Bow")
class Cat(Animal):
    def makeSound(self):
        print("Meow Meow")
    pass
        
wild_animal = Animal("Brown")
puppy = Dog("White")
kitten = Cat("Black")
wild_animal.makeSound()
kitten.makeSound()

Making Sound
Meow Meow


### create a text.file

In [40]:
with open("amjad.txt","w") as file:
    file.writelines("Hello everyone this amjad!!!!!!")

## CSV handling

In [41]:
import csv

In [42]:
with open("khan.csv","w") as file:
    write_obj = csv.writer(file)
    write_obj.writerow(['Name','Age','Contact no'])
    write_obj.writerow(['Amjad','30','9393842525'])

In [43]:
with open("khan.csv","r") as file:
    read_obj = csv.reader(file)
    for i in read_obj:
        print(i)


['Name', 'Age', 'Contact no']
[]
['Amjad', '30', '9393842525']
[]
